src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Doctrine\ORM\Mapping\PrePersist;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ArticleRepository::class), HasLifecycleCallbacks]
#[Vich\Uploadable]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'string', length: 255)]
    private $cover;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTime $date_created;

    #[ORM\Column(type: 'string', length: 255)]
    #[Gedmo\Slug(fields: ['title'])]
    private $slug;

    #[Vich\UploadableField(mapping: 'covers', fileNameProperty: 'cover')]
    private ?File $imageFile = null;

    public function setImageFile(File $cover = null)
    {
        $this->imageFile = $cover;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setCover($cover)
    {
        $this->cover = $cover;
    }

    public function getCover()
    {
        return $this->cover;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDateCreated(): ?\DateTime
    {
        return $this->date_created;
    }

    #[PrePersist]
    public function setDateCreated(): self
    {
        $this->date_created = new \DateTime();
        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function __toString(): string
    {
        return $this->cover;
    }
}

src/Controller/Admin/ArticleCrudController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Article;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class ArticleCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Article::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->addFormTheme('@FOSCKEditor/Form/ckeditor_widget.html.twig')
            ;
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('title', 'Titre'),
            TextareaField::new('content', 'Contenu')->setFormType(CKEditorType::class)->hideOnIndex(),
            ImageField::new('cover')->setBasePath('/uploads/covers')->onlyOnIndex(),
            TextField::new('imageFile')->setFormType(VichImageType::class)->onlyWhenCreating(),
            DateTimeField::new('date_created', 'Date Création')->hideOnForm()->setFormat('short'),
        ];
    }
}

src/Controller/Admin/DashboardController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Article;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractDashboardController
{
    #[Route('/admin', name: 'admin')]
    public function index(): Response
    {
        return $this->render('admin/dashboard.html.twig');
    }

    public function configureDashboard(): Dashboard
    {
        return Dashboard::new()
            ->setTitle('WebGroup Blog');
    }

    public function configureMenuItems(): iterable
    {
        yield MenuItem::linkToDashboard('Dashboard', 'fa fa-home');

        yield MenuItem::section('Articles');
        yield MenuItem::linkToCrud('Articles', 'fa fa-newspaper', Article::class)->setCssClass('text-custom-400');
        yield MenuItem::linkToCrud('Créer Article', 'fa fa-pen', Article::class)->setAction('new');
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/article')]
class ArticleController extends AbstractController
{
    #[Route('/{slug}', name: 'article_show', methods: ['GET', 'POST'])]
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('home/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }
}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.title }} | {{ parent() }}{% endblock %}

{% block head %}
    {{ parent() }}
    <meta property="og:url"
          content="http://xipelgames.tech/article/{{ article.id }}"/>
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="{{ article.title }}"/>
{% endblock %}

{% block body %}
    <a href="{{ path("app_home") }}" class="button rounded">Retour</a>
    <article class="rounded bg-white overflow-hidden article">
        <img src="{{ vich_uploader_asset(article, 'imageFile') }}" alt="Photo espace" class="w-full article-cover">

        <div class="article-wrapper grid gap-30">
            <h1 class="text-center">{{ article.title }}</h1>
            <p class="article-content">{{ article.content | raw }}</p>

            <span class="article-date">Publié le {{ article.dateCreated|format_datetime(pattern="dd MM YY", locale='fr') }} à {{ article.dateCreated|format_datetime('none', 'short', locale='fr') }}</span>
        </div>

    </article>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {{ include('includes/header.html.twig') }}
        <main class="flex justify-center">
            <section class="wrapper w-full">
                {% block body %}

                {% endblock %}
            </section>
        </main>
        {{ include('includes/footer.html.twig') }}
    </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil | {{ parent() }}{% endblock %}

{% block head %}
    {{ parent() }}
    <meta property="og:type" content="siteweb"/>
    <meta property="og:title" content="Space Blog | Site communautaire."/>
    <meta property="og:description"
          content="Space Blog est un blog autour de l'espace'. Retrouvez des articles en fonction de vos envies."/>
    <meta property="og:image"
          content="{{ app.request.schemeAndHttpHost ~ app.request.baseUrl }}{{ asset('images/website/logo.svg') }}"/>
{% endblock %}

{% block body %}
    <section style="background-image: url('{{ asset('images/hero.jpeg') }}')"
             class="w-full hero rounded background-cover background-center no-repeat relative flex items-center">
        <h1 class="hero-text absolute w-half text-right text-white">DECOUVREZ <span class="strong">L'ESPACE</span><br>
            COMME JAMAIS<br> AUPARAVANT</h1>
    </section>

    <h2>Nos articles</h2>

    <div class="flex justify-between wrap">
        {% for article in articles %}
            <article class="article-card rounded overflow-hidden">
                <a href="{{ path('article_show', {slug: article.slug }) }}" class="w-full h-full">
                    <img src="{{ vich_uploader_asset(article, 'imageFile') }}" alt="Photo espace" class="w-full article-card-cover">
                    <h3 class="article-card-title">{{ article.title }}</h3>
                </a>
            </article>
        {% endfor %}
    </div>
{% endblock %}

templates/includes/footer.html.twig
<footer class="footer flex items-center justify-center flex-col">
    <img src="{{ asset('images/logospaceblogfooter.svg') }}" alt="Logo SpaceBlog" class="opacity-8">
    <p class="logo-footer opacity-8">SpaceBlog</p>
</footer>

templates/includes/header.html.twig
<header class="flex justify-center">
    <div class="wrapper w-full">
        <a href="{{ path('app_home') }}" class="flex h-full items-center">
            <img src="{{ asset('images/logospaceblog.svg') }}" alt="Logo SpaceBlog" class="logo">
            <p class="logo-text">SpaceBlog</p>
        </a>
    </div>
</header>